# Generated by Django 5.2.18 on 2026-10-09 15:55

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Tên dự án')),
                ('summary', models.TextField(verbose_name='Mô tả ngắn')),
                ('stack', models.JSONField(blank=True, default=list, verbose_name='Công nghệ')),
                ('year', models.CharField(max_length=10, verbose_name='Năm')),
                ('image', models.CharField(max_length=500, verbose_name='Ảnh đại diện')),
                ('color', models.CharField(max_length=30, verbose_name='Màu nhấn')),
                ('role', models.CharField(max_length=150, verbose_name='Vai trò')),
                ('content', models.TextField(verbose_name='Nội dung chi tiết (Markdown)')),
                ('live_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link demo')),
                ('github_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link GitHub')),
                ('featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'dự án',
                'verbose_name_plural': 'Dự án',
                'db_table': 'Projects',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('slug', models.SlugField(db_index=False, max_length=150, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Tên dự án')),
                ('summary', models.TextField(verbose_name='Mô tả ngắn')),
                ('stack', models.JSONField(blank=True, default=list, verbose_name='Công nghệ')),
                ('year', models.CharField(max_length=10, verbose_name='Năm')),
                ('image', models.CharField(max_length=500, verbose_name='Ảnh đại diện')),
                ('color', models.CharField(max_length=30, verbose_name='Màu nhấn')),
                ('role', models.CharField(max_length=150, verbose_name='Vai trò')),
                ('content', models.TextField(verbose_name='Nội dung chi tiết (Markdown)')),
                ('live_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link demo')),
                ('github_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link GitHub')),
                ('featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-updated_at', 'id'], name='Projects_updated_f53e23_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['featured'], name='Projects_feature_8c5f69_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='project',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "projects_projectevent" ("color", "content", "created_at", "created_by_id", "deleted_at", "description", "featured", "github_url", "id", "image", "is_active", "live_url", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "slug", "stack", "summary", "title", "updated_at", "updated_by_id", "year") VALUES (NEW."color", NEW."content", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."featured", NEW."github_url", NEW."id", NEW."image", NEW."is_active", NEW."live_url", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role", NEW."slug", NEW."stack", NEW."summary", NEW."title", NEW."updated_at", NEW."updated_by_id", NEW."year"); RETURN NULL;', hash='74cf9259ea10e5f5c73645a0b4825391c8fafc6a', operation='INSERT', pgid='pgtrigger_insert_insert_2e147', table='Projects', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='project',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "projects_projectevent" ("color", "content", "created_at", "created_by_id", "deleted_at", "description", "featured", "github_url", "id", "image", "is_active", "live_url", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "slug", "stack", "summary", "title", "updated_at", "updated_by_id", "year") VALUES (NEW."color", NEW."content", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."featured", NEW."github_url", NEW."id", NEW."image", NEW."is_active", NEW."live_url", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role", NEW."slug", NEW."stack", NEW."summary", NEW."title", NEW."updated_at", NEW."updated_by_id", NEW."year"); RETURN NULL;', hash='36f0a4b50e85aafab2adecdf5603000b7bb3680c', operation='UPDATE', pgid='pgtrigger_update_update_804c3', table='Projects', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='project',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "projects_projectevent" ("color", "content", "created_at", "created_by_id", "deleted_at", "description", "featured", "github_url", "id", "image", "is_active", "live_url", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "slug", "stack", "summary", "title", "updated_at", "updated_by_id", "year") VALUES (OLD."color", OLD."content", OLD."created_at", OLD."created_by_id", OLD."deleted_at", OLD."description", OLD."featured", OLD."github_url", OLD."id", OLD."image", OLD."is_active", OLD."live_url", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."role", OLD."slug", OLD."stack", OLD."summary", OLD."title", OLD."updated_at", OLD."updated_by_id", OLD."year"); RETURN NULL;', hash='cf3d11d846cf58ca5c2dee9cc28f5ef20d50c474', operation='DELETE', pgid='pgtrigger_delete_delete_2192f', table='Projects', when='AFTER')),
        ),
    ]
