# Generated by Django 5.2.18 on 2026-10-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(max_length=30, verbose_name='Năm'),
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='year',
            field=models.CharField(max_length=30, verbose_name='Năm'),
        ),
    ]
