# Generated by Django 5.2.18 on 2026-10-09 15:55

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('excerpt', models.TextField(verbose_name='Đoạn trích')),
                ('published_date', models.CharField(max_length=30, verbose_name='Ngày đăng')),
                ('category', models.CharField(max_length=100, verbose_name='Chuyên mục')),
                ('read_time', models.CharField(max_length=30, verbose_name='Thời gian đọc')),
                ('image', models.CharField(max_length=500, verbose_name='Ảnh đại diện')),
                ('content', models.TextField(verbose_name='Nội dung (Markdown)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'bài viết',
                'verbose_name_plural': 'Bài viết',
                'db_table': 'Blogs',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlogEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('slug', models.SlugField(db_index=False, max_length=150, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('excerpt', models.TextField(verbose_name='Đoạn trích')),
                ('published_date', models.CharField(max_length=30, verbose_name='Ngày đăng')),
                ('category', models.CharField(max_length=100, verbose_name='Chuyên mục')),
                ('read_time', models.CharField(max_length=30, verbose_name='Thời gian đọc')),
                ('image', models.CharField(max_length=500, verbose_name='Ảnh đại diện')),
                ('content', models.TextField(verbose_name='Nội dung (Markdown)')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='blogs.blog')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['-updated_at', 'id'], name='Blogs_updated_371c04_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['category'], name='Blogs_categor_b94b80_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='blog',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "blogs_blogevent" ("category", "content", "created_at", "created_by_id", "deleted_at", "description", "excerpt", "id", "image", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published_date", "read_time", "slug", "title", "updated_at", "updated_by_id") VALUES (NEW."category", NEW."content", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."excerpt", NEW."id", NEW."image", NEW."is_active", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."published_date", NEW."read_time", NEW."slug", NEW."title", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='bbda4d2b8fc9a97b5de6d3a3ee2c8180cb051a9f', operation='INSERT', pgid='pgtrigger_insert_insert_fc382', table='Blogs', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='blog',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "blogs_blogevent" ("category", "content", "created_at", "created_by_id", "deleted_at", "description", "excerpt", "id", "image", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published_date", "read_time", "slug", "title", "updated_at", "updated_by_id") VALUES (NEW."category", NEW."content", NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."excerpt", NEW."id", NEW."image", NEW."is_active", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."published_date", NEW."read_time", NEW."slug", NEW."title", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='819521e330debb7ca0a2bcdc6ed84872d3339ed6', operation='UPDATE', pgid='pgtrigger_update_update_54ce7', table='Blogs', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='blog',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "blogs_blogevent" ("category", "content", "created_at", "created_by_id", "deleted_at", "description", "excerpt", "id", "image", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "published_date", "read_time", "slug", "title", "updated_at", "updated_by_id") VALUES (OLD."category", OLD."content", OLD."created_at", OLD."created_by_id", OLD."deleted_at", OLD."description", OLD."excerpt", OLD."id", OLD."image", OLD."is_active", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."published_date", OLD."read_time", OLD."slug", OLD."title", OLD."updated_at", OLD."updated_by_id"); RETURN NULL;', hash='2471a64ff37e4e20e8c8d74d3366e7881c09dc8f', operation='DELETE', pgid='pgtrigger_delete_delete_715e1', table='Blogs', when='AFTER')),
        ),
    ]
