# Generated by Django 5.2.18 on 2026-10-09 15:55

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('name', models.CharField(max_length=150, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'liên hệ',
                'verbose_name_plural': 'Liên hệ',
                'db_table': 'Contacts',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật gần nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xóa mềm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú kỹ thuật')),
                ('name', models.CharField(max_length=150, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='contacts.contact')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['-created_at', 'id'], name='Contacts_created_c5f2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='Contacts_email_623aff_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contact',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "contacts_contactevent" ("created_at", "created_by_id", "deleted_at", "description", "email", "id", "is_active", "message", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."email", NEW."id", NEW."is_active", NEW."message", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='9aa9beacfc222c4784fe0a4e7f68fba963435a02', operation='INSERT', pgid='pgtrigger_insert_insert_60225', table='Contacts', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contact',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "contacts_contactevent" ("created_at", "created_by_id", "deleted_at", "description", "email", "id", "is_active", "message", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."deleted_at", NEW."description", NEW."email", NEW."id", NEW."is_active", NEW."message", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;', hash='3b87f6ec4e2ea8e14369420be8c7dd06d04e237d', operation='UPDATE', pgid='pgtrigger_update_update_7498c', table='Contacts', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contact',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "contacts_contactevent" ("created_at", "created_by_id", "deleted_at", "description", "email", "id", "is_active", "message", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by_id") VALUES (OLD."created_at", OLD."created_by_id", OLD."deleted_at", OLD."description", OLD."email", OLD."id", OLD."is_active", OLD."message", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at", OLD."updated_by_id"); RETURN NULL;', hash='fc50de9fc5fcb255e4fd33978e3cf0bc5768abe9', operation='DELETE', pgid='pgtrigger_delete_delete_e2e36', table='Contacts', when='AFTER')),
        ),
    ]
